# Generated by Django 4.1.13 on 2024-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_priming', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('content_delivery', models.CharField(choices=[('scheduled', 'Scheduled'), ('real_time', 'Real-Time')], max_length=50)),
                ('exposure_maximization', models.CharField(choices=[('viral', 'Viral'), ('organic', 'Organic'), ('paid', 'Paid')], max_length=50)),
                ('online_harms', models.CharField(choices=[('trolling', 'Trolling'), ('fake_news', 'Fake News'), ('phishing', 'Phishing')], max_length=50)),
                ('offline_activity', models.CharField(choices=[('protests', 'Protests'), ('rallies', 'Rallies'), ('campaigns', 'Campaigns')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('offensive', 'Offensive'), ('defensive', 'Defensive'), ('neutral', 'Neutral')], max_length=50)),
                ('objective', models.CharField(choices=[('disrupt', 'Disrupt'), ('influence', 'Influence'), ('monitor', 'Monitor')], max_length=50)),
                ('target_audience_analysis', models.CharField(choices=[('public', 'General Public'), ('military', 'Military'), ('political', 'Political')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=50)),
                ('content', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image')], max_length=50)),
                ('legitimacy', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
                ('microtarget', models.CharField(choices=[('demographics', 'Demographics'), ('behavioral', 'Behavioral'), ('geographical', 'Geographical')], max_length=50)),
                ('channels', models.CharField(choices=[('social_media', 'Social Media'), ('news', 'News'), ('blogs', 'Blogs')], max_length=50)),
                ('affordance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
            ],
        ),
    ]
