# Generated by Django 4.1.13 on 2024-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='strategy_details',
            new_name='degrade_adversary_details',
        ),
        migrations.AddField(
            model_name='plan',
            name='determine_target_ends_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='target_audience_adversaries_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
