# Generated by Django 4.1.13 on 2024-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_strategy_details_plan_degrade_adversary_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='degrade_adversary_details',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='determine_target_ends_details',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='target_audience_adversaries_details',
        ),
        migrations.AddField(
            model_name='plan',
            name='additional_details',
            field=models.JSONField(blank=True, help_text='Additional details based on selected choices', null=True),
        ),
    ]
